#!/bin/bash
#BSUB -J Main_Script_2
#BSUB -o outfiles/Main_Script_2%J.out
#BSUB -e outfiles/Main_Script_2%J.err
#BSUB -q hpc
#BSUB -n 4
#BSUB -R "rusage[mem=100GB]"
#BSUB -R "span[hosts=1]"
#BSUB -W 08:00
# end of BSUB options

cd "$LS_SUBCWD" || exit 1

module purge
module load python3/3.12.11

source .venv/bin/activate

export OMP_NUM_THREADS=$LSB_DJOB_NUMPROC
export OPENBLAS_NUM_THREADS=$LSB_DJOB_NUMPROC
export MKL_NUM_THREADS=$LSB_DJOB_NUMPROC
export NUMEXPR_NUM_THREADS=$LSB_DJOB_NUMPROC
export MKL_DYNAMIC=false
export OMP_DYNAMIC=false

export LS_DIM=2
export INDEX=10000
export WEIGHTING=false
python src/dna_modelling/main.py
